apiVersion: v1
kind: Service
metadata:
  name: external-vote
spec:
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
