apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}
  labels:
    {{- include "mycharts.labels" . |
    nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mycharts.selectorLabels" . |
      nindent 6 }}
  template:
    metadata:
      name: {{ .Values.deploy.podName }}
      labels:
        {{- include "mycharts.selectorLabels" . |
      nindent 8 }}

    spec:
      containers:
        - name: {{ .Values.deploy.containerName }}
          image: {{ .Values.deploy.image | quote }}